import { NextResponse } from 'next/server'
import { z } from 'zod'
import { requireUser } from '@/lib/server/auth'
import { apiErrorResponse, ApiError } from '@/lib/server/errors'
import { createAdminClient } from '@/lib/supabase/admin'

const subscriptionSchema=z.object({endpoint:z.string().url().max(2048).refine((value)=>value.startsWith('https://'),'A secure push endpoint is required.'),keys:z.object({auth:z.string().min(8).max(500),p256dh:z.string().min(20).max(500)})})
export async function POST(request:Request){try{const session=await requireUser();const raw=await request.json();const subscription=subscriptionSchema.parse(raw.subscription||raw);const admin=createAdminClient();const{data:existing}=await admin.from('push_subscriptions').select('user_id').eq('endpoint',subscription.endpoint).maybeSingle();if(existing&&existing.user_id!==session.user.id)throw new ApiError(409,'This browser subscription belongs to another account. Reset site notifications and try again.','SUBSCRIPTION_CONFLICT');const payload={user_id:session.user.id,endpoint:subscription.endpoint,keys_auth:subscription.keys.auth,keys_p256dh:subscription.keys.p256dh};const{error}=existing?await admin.from('push_subscriptions').update(payload).eq('endpoint',subscription.endpoint).eq('user_id',session.user.id):await admin.from('push_subscriptions').insert(payload);if(error)throw error;return NextResponse.json({success:true})}catch(error){return apiErrorResponse(error)}}
export async function DELETE(request:Request){try{const session=await requireUser();const{endpoint}=z.object({endpoint:z.string().url().max(2048)}).parse(await request.json());const{error}=await createAdminClient().from('push_subscriptions').delete().eq('endpoint',endpoint).eq('user_id',session.user.id);if(error)throw error;return NextResponse.json({success:true})}catch(error){return apiErrorResponse(error)}}
