'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'
import { Bike, ChefHat, Clock3, History, LayoutDashboard, RefreshCw, Settings, ShoppingBag, Utensils } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import toast from 'react-hot-toast'
import MenuManager from './MenuManager'
import StoreSettings from './StoreSettings'

type Item = { id: string; item_name: string; size_label: string; quantity: number; cancelled_quantity: number; addon_labels: string[] | null }
type Order = {
  id: string; order_number: number | null; created_at: string; customer_name: string; customer_phone: string; total_paise: number
  fulfillment_status: string; payment_method: string; payment_status: string; delivery_type: string; delivery_status: string
  delivery_boy_id: string | null; delivery_house?: string | null; delivery_area?: string | null; delivery_landmark?: string | null; delivery_city?: string | null
  notes?: string | null; order_items: Item[]
}
type Driver = { user_id: string; is_active: boolean; is_approved: boolean; vehicle_number: string | null; profile: { full_name: string | null; phone: string | null } | null }
type Tab = 'orders' | 'history' | 'drivers' | 'menu' | 'settings'
const money = (paise: number) => `₹${(paise / 100).toFixed(2)}`
const statusName: Record<string,string> = { awaiting_payment:'Payment pending',awaiting_acceptance:'New order',accepted:'Accepted',preparing:'Preparing',ready:'Ready',assigned:'Driver assigned',picked_up:'Out for delivery',completed:'Completed',delivered:'Delivered',cancellation_pending:'Cancellation pending',cancelled:'Cancelled',payment_failed:'Payment failed' }

export default function AdminDashboard() {
  const [orders,setOrders]=useState<Order[]>([]), [drivers,setDrivers]=useState<Driver[]>([]), [loading,setLoading]=useState(true)
  const [tab,setTab]=useState<Tab>('orders'), [busy,setBusy]=useState<string|null>(null), [search,setSearch]=useState('')
  const [partner,setPartner]=useState({fullName:'',phone:'',vehicleNumber:'',password:'',otp:'',verificationId:''})
  const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{const response=await fetch('/api/admin/dashboard',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Dashboard unavailable.');setOrders(data.orders);setDrivers(data.drivers)}catch(error){toast.error(error instanceof Error?error.message:'Dashboard unavailable.')}finally{if(!silent)setLoading(false)}},[])
  useEffect(()=>{load();const timer=window.setInterval(()=>load(true),15000);return()=>window.clearInterval(timer)},[load])

  const request=async(url:string,body:object)=>{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Action failed.');return data}
  const act=async(orderId:string,action:'accept'|'prepare'|'ready'|'complete')=>{setBusy(orderId);try{await request('/api/admin/orders/transition',{orderId,action});toast.success('Order updated.');await load(true)}catch(error){toast.error(error instanceof Error?error.message:'Action failed.')}finally{setBusy(null)}}
  const cancel=async(orderId:string)=>{const reason=window.prompt('Cancellation/rejection reason:')?.trim();if(!reason)return;setBusy(orderId);try{await request('/api/orders/cancel',{orderId,reason});toast.success('Order cancelled.');await load(true)}catch(error){toast.error(error instanceof Error?error.message:'Cancellation failed.')}finally{setBusy(null)}}
  const assign=async(orderId:string,driverId:string)=>{if(!driverId)return;setBusy(orderId);try{await request('/api/admin/assign-driver',{orderId,driverId});toast.success('Driver assigned.');await load(true)}catch(error){toast.error(error instanceof Error?error.message:'Assignment failed.')}finally{setBusy(null)}}
  const setDriverApproval=async(driver:Driver)=>{setBusy(`driver-${driver.user_id}`);try{await request('/api/admin/drivers/status',{driverId:driver.user_id,approved:!driver.is_approved});toast.success(driver.is_approved?'Delivery partner suspended.':'Delivery partner approved.');await load(true)}catch(error){toast.error(error instanceof Error?error.message:'Partner status could not be changed.')}finally{setBusy(null)}}
  const sendPartnerOtp=async()=>{try{const data=await request('/api/admin/send-partner-otp',{phone:partner.phone});setPartner((v)=>({...v,verificationId:data.verificationId}));toast.success('Code sent to delivery partner.')}catch(error){toast.error(error instanceof Error?error.message:'Code could not be sent.')}}
  const addPartner=async(event:FormEvent)=>{event.preventDefault();setBusy('partner');try{await request('/api/admin/add-partner',partner);toast.success('Delivery partner approved.');setPartner({fullName:'',phone:'',vehicleNumber:'',password:'',otp:'',verificationId:''});await load(true)}catch(error){toast.error(error instanceof Error?error.message:'Partner could not be added.')}finally{setBusy(null)}}

  const active=orders.filter((o)=>!['completed','delivered','cancelled','payment_failed'].includes(o.fulfillment_status))
  const history=orders.filter((o)=>['completed','delivered','cancelled','payment_failed'].includes(o.fulfillment_status))
  const shown=(tab==='history'?history:active).filter((o)=>`${o.order_number} ${o.customer_name} ${o.customer_phone}`.toLowerCase().includes(search.toLowerCase()))
  const today=new Date().toDateString();const completedToday=orders.filter((o)=>['completed','delivered'].includes(o.fulfillment_status)&&new Date(o.created_at).toDateString()===today)
  const prepMap=new Map<string,number>();active.filter((o)=>['accepted','preparing'].includes(o.fulfillment_status)).forEach((o)=>o.order_items.forEach((item)=>prepMap.set(`${item.item_name} (${item.size_label})`,(prepMap.get(`${item.item_name} (${item.size_label})`)||0)+item.quantity-item.cancelled_quantity)));const prepSummary=[...prepMap.entries()]

  const actionButtons=(order:Order)=> <div className="mt-4 flex flex-wrap items-center gap-2">
    {order.fulfillment_status==='awaiting_acceptance'?<button onClick={()=>act(order.id,'accept')} className="rounded-lg bg-sage px-3 py-2 text-xs font-bold text-white">Accept order</button>:null}
    {order.fulfillment_status==='accepted'?<button onClick={()=>act(order.id,'prepare')} className="rounded-lg bg-amber-600 px-3 py-2 text-xs font-bold text-white">Start preparing</button>:null}
    {order.fulfillment_status==='preparing'?<button onClick={()=>act(order.id,'ready')} className="rounded-lg bg-sage px-3 py-2 text-xs font-bold text-white">Mark ready</button>:null}
    {order.fulfillment_status==='ready'&&order.delivery_type!=='delivery'?<button onClick={()=>act(order.id,'complete')} className="rounded-lg bg-sage px-3 py-2 text-xs font-bold text-white">Complete handover</button>:null}
    {order.fulfillment_status==='ready'&&order.delivery_type==='delivery'&&order.delivery_status==='unassigned'?<select aria-label="Assign delivery partner" defaultValue="" onChange={(e)=>assign(order.id,e.target.value)} className="rounded-lg border border-linen px-3 py-2 text-xs"><option value="" disabled>Assign active driver</option>{drivers.filter((d)=>d.is_active&&d.is_approved).map((d)=><option key={d.user_id} value={d.user_id}>{d.profile?.full_name||'Driver'} · {d.vehicle_number}</option>)}</select>:null}
    {['awaiting_payment','awaiting_acceptance','accepted','preparing','ready'].includes(order.fulfillment_status)?<button onClick={()=>cancel(order.id)} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Cancel / reject</button>:null}
    <a href={`/api/orders/${order.id}/receipt`} className="rounded-lg border border-linen px-3 py-2 text-xs font-semibold">Receipt</a>
  </div>

  const metrics: Array<[string, string | number, LucideIcon]> = [
    ['New',active.filter((o)=>o.fulfillment_status==='awaiting_acceptance').length,Clock3],['Preparing',active.filter((o)=>['accepted','preparing'].includes(o.fulfillment_status)).length,ChefHat],['Ready / delivery',active.filter((o)=>['ready','assigned','picked_up'].includes(o.fulfillment_status)).length,Bike],['Today revenue',money(completedToday.reduce((sum,o)=>sum+o.total_paise,0)),ShoppingBag]
  ]
  const ordersView=<><div className="mb-5 grid gap-3 sm:grid-cols-4">{metrics.map(([label,value,Icon])=><div key={String(label)} className="rounded-xl border border-linen bg-white p-4"><Icon className="mb-2 text-sage" size={18}/><p className="text-xs text-cocoa-muted">{String(label)}</p><p className="text-xl font-bold text-cocoa">{String(value)}</p></div>)}</div>
  {tab==='orders'&&prepSummary.length?<section className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><h2 className="mb-2 font-semibold text-amber-900">Kitchen preparation summary</h2><div className="flex flex-wrap gap-2">{prepSummary.map(([item,count])=><span key={item} className="rounded-full bg-white px-3 py-1 text-xs">{count} × {item}</span>)}</div></section>:null}
  <div className="mb-4 flex items-center gap-3"><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search order, customer or phone" className="w-full max-w-md rounded-xl border border-linen bg-white px-4 py-3 text-sm"/><button onClick={()=>load()} className="rounded-xl border border-linen bg-white p-3" aria-label="Refresh"><RefreshCw size={17}/></button></div>
  {loading?<p className="p-8 text-center text-cocoa-muted">Loading orders…</p>:<div className="grid gap-4 xl:grid-cols-2">{shown.map((order)=><article key={order.id} className={`rounded-2xl border bg-white p-5 shadow-sm ${order.fulfillment_status==='awaiting_acceptance'?'border-amber-300':'border-linen'}`}><div className="flex justify-between gap-3"><div><p className="font-bold text-cocoa">#{order.order_number||order.id.slice(0,8)} · {order.customer_name}</p><p className="text-xs text-cocoa-muted">{order.customer_phone} · {new Date(order.created_at).toLocaleString('en-IN')}</p></div><div className="text-right"><span className="rounded-full bg-sage/10 px-3 py-1 text-xs font-semibold text-sage-dark">{statusName[order.fulfillment_status]||order.fulfillment_status}</span><p className="mt-2 font-bold">{money(order.total_paise)}</p></div></div><div className="my-4 space-y-2 border-y border-linen py-3">{order.order_items.map((item)=><div key={item.id} className="flex justify-between text-sm"><span>{item.quantity-item.cancelled_quantity} × {item.item_name} <em className="text-cocoa-muted">({item.size_label})</em></span>{item.addon_labels?.length?<span className="text-xs text-sage-dark">{item.addon_labels.join(', ')}</span>:null}</div>)}</div><p className="text-xs text-cocoa-muted">{order.delivery_type.replace('_',' ')} · {order.payment_method==='cod'?'COD':'Online'} ({order.payment_status})</p>{order.delivery_type==='delivery'?<p className="mt-1 text-xs text-cocoa-muted">{[order.delivery_house,order.delivery_area,order.delivery_landmark,order.delivery_city].filter(Boolean).join(', ')||'Address unavailable'} · {order.delivery_status}</p>:null}{order.notes?<p className="mt-2 rounded-lg bg-cream p-2 text-xs">Note: {order.notes}</p>:null}<fieldset disabled={busy===order.id}>{actionButtons(order)}</fieldset></article>)}</div>}</>

  return <div className="mx-auto max-w-7xl p-4 sm:p-6"><nav className="mb-6 flex flex-wrap gap-2">{[
    ['orders','Live orders',LayoutDashboard],['history','History',History],['drivers','Drivers',Bike],['menu','Menu',Utensils],['settings','Settings',Settings]
  ].map(([id,label,Icon])=><button key={String(id)} onClick={()=>setTab(id as Tab)} className={`flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold ${tab===id?'bg-cocoa text-white':'border border-linen bg-white text-cocoa'}`}><Icon size={16}/>{String(label)}</button>)}</nav>
  {(tab==='orders'||tab==='history')?ordersView:null}
  {tab==='menu'?<MenuManager/>:null}{tab==='settings'?<StoreSettings/>:null}
  {tab==='drivers'?<div className="grid gap-6 lg:grid-cols-[1fr_1.2fr]"><form onSubmit={addPartner} className="rounded-2xl border border-linen bg-white p-5"><h2 className="mb-4 font-display text-xl">Approve delivery partner</h2><div className="space-y-3"><input placeholder="Full name" value={partner.fullName} onChange={(e)=>setPartner({...partner,fullName:e.target.value})} className="w-full rounded-lg border border-linen p-3"/><input placeholder="Mobile number (+91…)" value={partner.phone} onChange={(e)=>setPartner({...partner,phone:e.target.value})} className="w-full rounded-lg border border-linen p-3"/><input placeholder="Vehicle number" value={partner.vehicleNumber} onChange={(e)=>setPartner({...partner,vehicleNumber:e.target.value})} className="w-full rounded-lg border border-linen p-3"/><input type="password" placeholder="Temporary login password" value={partner.password} onChange={(e)=>setPartner({...partner,password:e.target.value})} className="w-full rounded-lg border border-linen p-3"/>{partner.verificationId?<input placeholder="SMS verification code" value={partner.otp} onChange={(e)=>setPartner({...partner,otp:e.target.value})} className="w-full rounded-lg border border-linen p-3"/>:null}</div>{partner.verificationId?<button disabled={busy==='partner'} className="mt-4 rounded-lg bg-sage px-4 py-2 font-bold text-white">Create partner account</button>:<button type="button" onClick={sendPartnerOtp} className="mt-4 rounded-lg bg-cocoa px-4 py-2 font-bold text-white">Send verification code</button>}</form><section className="rounded-2xl border border-linen bg-white p-5"><h2 className="mb-4 font-display text-xl">Delivery partners</h2><div className="space-y-3">{drivers.map((driver)=><div key={driver.user_id} className="rounded-xl bg-cream p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{driver.profile?.full_name||'Unnamed driver'}</p><p className="text-xs text-cocoa-muted">{driver.profile?.phone} · {driver.vehicle_number}</p></div><span className={`text-xs font-bold ${driver.is_active?'text-sage-dark':'text-cocoa-muted'}`}>{driver.is_approved?(driver.is_active?'On duty':'Off duty'):'Suspended'}</span></div><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-cocoa-muted">Active assignments: {orders.filter((o)=>o.delivery_boy_id===driver.user_id&&!['delivered','cancelled'].includes(o.fulfillment_status)).length}</p><button type="button" disabled={busy===`driver-${driver.user_id}`} onClick={()=>setDriverApproval(driver)} className={`rounded-lg border px-3 py-1.5 text-xs font-semibold disabled:opacity-50 ${driver.is_approved?'border-red-200 text-red-700':'border-sage/30 text-sage-dark'}`}>{driver.is_approved?'Suspend':'Approve'}</button></div></div>)}</div></section></div>:null}
  </div>
}
